
name: Build & Push Docker image

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        env:
          IMAGE_TAG: ${{ github.sha }}
          USER: ${{ secrets.DOCKERHUB_USERNAME }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: USER/docker-rest-api:IMAGE_TAG
